[package]
name = "amethyst-rhusics"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { git = "https://github.com/Rhuagh/amethyst", branch = "fix/update-shrev" }
rhusics = { git = "https://github.com/Rhuagh/rhusics", features = ["ecs"], branch = "feature/optional-shape-contacts" }
genmesh = "0.5"
rand = "0.3"
